# Config file for automatic testing at travis-ci.org

language: python

install:
  - pip install coveralls

python:
  - "2.7"

# command to install dependencies and run tests
script: 
  coverage run --source=bootstrap_cfn setup.py test

after_success:
  coveralls
  
